export const paths = {
  home: "/",
  explore: "/explore",
  profile: "/profile",
  security_questions: "/security-questions",
  settings: "/settings",
  profileDetail: "/profile-detail",
  application: "/application",
  login: "/login",
  regiter: "/register",
  upload: "/upload",
  upload_process: "/upload/process",
  otp: "/otp",
  noti: "/notifications",
  system_noti: "/notifications/system",
  balance_noti: "/notifications/balance",
  recommand_more: "/rec_more",
  wallet: "/wallet",
  wallet_invite: "/wallet/invite",
  wallet_history: "/wallet/Transition",
  wallet_recharge : '/wallet/recharge',
  wallet_withdraw : '/wallet/withdraw',
};
